name: Build and Test 
description: Builds and tests the .NET project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Test
      run: dotnet build --configuration Release && dotnet test
      
