name: 'Build and Test'
description: 'Build and test a .NET Core project'

inputs:
  project-path:
    description: 'Path to the .NET Core project'
    required: true
    default: './'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Restore NuGet packages
      run: dotnet restore ${{ inputs.project-path }}

    - name: Build and Test
      run: dotnet build --configuration Release ${{ inputs.project-path }} && dotnet test ${{ inputs.project-path }}

