name: 'Build and Test'
description: 'Build and test a .NET Core project'

runs:
  using: 'composite'

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        cd ..
        dotnet build --configuration Release && dotnet test
